[book]
   title = "Demos Network Documentation"
   authors = ["KyneSys Labs"]
   language = "en"
   multilingual = false
   src = "src"  # adjust if your markdown files are elsewhere
   
   [build]
   build-dir = "book"  # this matches the artifact path in the action

[output.html]
default-theme = "light"
additional-css = ["theme/gitbook.css"]
additional-js = ["theme/gitbook.js"]
